services:
  db-postgres:
    image: postgres:17.5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: utilidades
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postdata:/var/lib/postgresql/data
  
  redis:
    image: redis:8.2.1
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_APPENDONLY=yes
  
  backend:
    image: utilidades:latest
    ports: [ "8088:80", "4443:443" ]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=korsa.dev
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/korsa.dev.pfx
    entrypoint: [ "dotnet", "Utilidades.Api.dll" ]
    volumes:
      - ./volumes/https:/https

volumes:
  volumes:
    driver: local
    driver_opts:
      type: none
      device: ./volumes
      o: bind