name: deploy.yml
on:
  push:
    branches:
      - pages
jobs:
  deploy:
    runs-on: windows-2019
    steps:
      - name: instala dotnet
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: '9.0.x'

      - name: restore
        run: dotnet restore

      - name: build
        run: dotnet build

      - name: publish
        run: dotnet publish -c Release -o publish
