name: deploy.yml
on:
  push:
    branches:
      - pages
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: instala dotnet
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: '9.0.x'

      - name: restore
        run: dotnet restore ./Utilidades.Api/

      - name: build
        run: dotnet build ./Utilidades.Api/

      - name: publish
        run: dotnet publish ./Utilidades.Api/ -c Release -o publish
